name: SBOM
on: [push, pull_request]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Get Python site-packages path
        id: sitepkgs
        run: echo "SITEPKGS=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM (Syft)
        run: syft $SITEPKGS -o cyclonedx-json=sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
      - name: Scan SBOM with Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: sbom
          input: sbom.json
          format: table
          output: trivy-sbom-results.txt
      - name: Upload Trivy SBOM Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-results
          path: trivy-sbom-results.txt